[package]
name = "fero-bastion"
version = "0.1.0"
authors = ["Alex Crawford <alex.crawford@coreos.com>"]
workspace = ".."

[dependencies]
chrono = "0.4"
failure = "0.1"
futures = "0.1"
grpcio = { git = "https://github.com/pingcap/grpc-rs" }
log = "0.4"
loggerv = "0.7"
protobuf = "2.0"
structopt = "0.2"

[dependencies.fero-proto]
path = "../fero-proto/"
